[package]
name = "hollowkey_api"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.37", features = ["full"] }
axum = "0.8.6"    
serde = { version = "1.0", features = ["derive"] }
